# Generated by Django 4.0.4 on 2022-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele_about', models.CharField(max_length=50)),
                ('descriptioni_about', models.TextField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categorie', models.CharField(max_length=50)),
                ('image_categorie', models.FileField(upload_to='Cate_imgs')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plat', models.CharField(max_length=50)),
                ('prix_reduction_plat', models.IntegerField()),
                ('description_platr', models.TextField()),
                ('image_plat', models.FileField(upload_to='plat_imgs')),
                ('prix_plat', models.IntegerField()),
                ('status_reduction_plat', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reservation', models.CharField(max_length=30)),
                ('num_reservation', models.IntegerField()),
                ('email_reservation', models.EmailField(max_length=254)),
                ('number_perso_reservation', models.IntegerField()),
                ('maps_reservation', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
