# Generated by Django 4.0.4 on 2022-05-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plat',
            old_name='description_platr',
            new_name='description_plat',
        ),
    ]
