# Generated by Django 4.0.4 on 2022-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0002_rename_description_platr_plat_description_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_about',
            field=models.FileField(default=1, upload_to='plat_imgs'),
            preserve_default=False,
        ),
    ]
