# Generated by Django 4.0.4 on 2022-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele_banner', models.CharField(max_length=50)),
                ('description_banner', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Open_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hour_open', models.TimeField()),
                ('hour_close', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resau_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('name_reseau_social', models.CharField(max_length=30)),
                ('links_reseau_social', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=50)),
                ('session_img_banner_site', models.URLField()),
                ('adresse_site', models.CharField(max_length=50)),
                ('phone_site', models.IntegerField()),
                ('email_site', models.EmailField(max_length=50)),
                ('description_site', models.TextField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delele_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
